### ISSUE TITLE
Fail to send to Limbo

### ISSUE THREAD

**Issue by DarianRepo** [xMdb/hypixel-guild-chat-bot#69]
This is a big problem as the other way to get in limbo efficiently is to spam. To avoid mutes you can make it spam a command that does not exist  (ex /limbospam)

To solve this, go to the guild chat bot folder and go to  events/minecraft/handler/login.js and add some spam like this:
![image](https://user-images.githubusercontent.com/64095223/154826518-e9cafcf6-12d7-4f31-b030-d93f23730c21.png)

**Comment by DarianRepo** [comment]
If it stops working, add more spam or change the command name

**Comment by xMdb** [comment]
A PR would be appreciated @DarianRepo

**Comment by xMdb** [comment]
ok then

**Comment by xMdb** [comment]
Will be fixed in https://github.com/hychat-mc/mineflayer as this is a legacy application. You still get sent to Limbo because of AFKing anyways.
